---
ansible_ssh_user: ec2-user
ansible_become: "yes"

openshift_deployment_type: openshift-enterprise

openshift_disable_check: disk_availability,docker_image_availability,docker_storage,memory_availability,package_availability,package_version

# uncomment below if registering to a Satellite server
#redhat_satellite_fqdn: satellite.example.com
#redhat_organization_id: mycompany
#redhat_activationkey: mykey

#Vinay Changed this
containerized: "True"
openshift_release: 3.9.30
openshift_image_tag: v3.9.30

oreg_url: registry.access.redhat.com/openshift3/ose-${component}:${version}
openshift_examples_modify_imagestreams: true

#Why 443 and not 8443 
openshift_master_api_port: 8443
openshift_master_console_port: 8443

# disable installation of broker when the core openshift is installed
#ansible_service_broker_install: False

# enable installation of broker separately after core openshift is installed
#override_ansible_service_broker_install: True
#template_service_broker_selector: {"region":"infra"}
# Proxy settings
#openshift_http_proxy: "http://proxy.example.com:8080"
#openshift_https_proxy: "http://proxy.example.com:8080"
openshift_no_proxy: 'local,localhost,localdomain,svc,my.openshift.domain.com'

# Identity configuration - IDM
# openshift_master_identity_providers: [{'name': 'IDM', 'challenge': 'true', 'login': 'true', 'kind': 'LDAPPasswordIdentityProvider', 'attributes': {'id': ['dn'], 'email': ['mail'], 'name': ['cn'], 'preferredUsername': ['uid']}, 'bindDN': 'cn=directory manager', 'bindPassword': 'password_here', 'insecure': 'true', 'url': 'ldap://ldapserver:389/cn=users,cn=accounts,dc=domain,dc=com?uid'}]

# Identity configuration - HTPASSWD
#openshift_master_identity_providers: [{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider','filename': '/etc/origin/master/htpasswd'}]
#openshift_master_htpasswd_file: "/usr/share/ansible/openshift-ansible/htpasswd/.htpasswd"
openshift_master_htpasswd_users: {'admin': 'my_admin_password_hash', 'user': 'my_user_password_hash'}

# Identity configuration - OpenID
#openshift_master_openid_ca_file: "{{ additional_assets }}/openidserver.crt"
#openshift_master_identity_providers: [{"name": "openid_auth", "login": "true", "challenge": "false", "kind": "OpenIDIdentityProvider", "client_id": "ocp01", "client_secret": "df685aee-253a-40e6-90aa-92686858115c", "claims": {"id": ["sub"], "preferredUsername": ["preferred_username"], "name": ["name"], "email": ["email"]}, "urls": {"authorize": "https://openidserver/auth/realms/master/protocol/openid-connect/auth", "token": "https://openidserver/auth/realms/master/protocol/openid-connect/token"}, "ca": "openidserver.crt"}]

# Identify Configuration - Active Directory
openshift_master_identity_providers: 
- name: "my_company"
  challenge: true 
  login: true 
  mappingMethod: claim 
  kind: LDAPPasswordIdentityProvider
  attributes:
    id: 
    - dn
    email: 
    - mail
    name: 
    - cn
    preferredUsername: 
    - sAMAccountName 
  bindDN: "CN=OpenShift_Svc_Accounts,OU=Service Accounts,OU=Administration,DC=subdomain,DC=company,DC=com"
  bindPassword: "bind_password_here"
  insecure: true 
  url: "ldap://ldapserver:389/DC=subdomain,DC=company,DC=com?sAMAccountName"
- name: htpasswd_auth
  login: true
  challenge: true
  kind: HTPasswdPasswordIdentityProvider
  filename: /etc/origin/master/htpasswd

# openshift_hosted_registry_storage_kind: glusterfs
openshift_master_cluster_method: native

# This is the internal facing DNS for masters
openshift_master_cluster_hostname: master.vvenkatapath.jnpr.com 

# This is the external facing DNS for masters
openshift_master_cluster_public_hostname: master.vvenkatapath.jnpr.com

# This is the external facing DNS for apps
#for use first infra node and do this: http://xip.io/ 

# wildcard domain for app routes
#openshift_master_default_subdomain: apps.vvenkatapath.jnpr.com 

#  Provide local certificate paths which will be deployed to masters
# openshift_master_named_certificates: [{"certfile": "/root/openshift.crt", "keyfile": "/root/openshift.key", "cafile": "/root/ca-chain.pem"}]
#openshift_master_overwrite_named_certificates: "True"
# openshift_hosted_router_certificate: {"certfile": "/root/wildcard.crt", "keyfile": "/root/wildcard.key", 'cafile': '/root/ca-chain.pem' }

# master certificate - change path below as required
#openshift_master_named_certificates: [{"certfile": "/home/ansible-user/cluster_setup/certificates/admin", "keyfile": "/home/ansible-user/cluster_setup/certificates/certificates/key"}]

#  Install the openshift examples
openshift_install_examples: "True"

# Audit logging
# openshift_master_audit_config: {"basicAuditEnabled": "True"}
# openshift_master_audit_config: {"enabled": "True", "auditFilePath": "/var/log/openpaas-oscp-audit/openpaas-oscp-audit.log", "maximumFileRetentionDays": 14, "maximumFileSizeMegabytes": 500, "maximumRetainedFiles": 5}

openshift_node_kubelet_args: {'image-gc-high-threshold': ['90'], 'image-gc-low-threshold': ['80']}
openshift_router_selector: "region=infra"
openshift_registry_selector: "region=infra"
# This need to be cni 
os_sdn_network_plugin_name: 'cni'

# custom sdn configuration - change to a different range as required
# osm_cluster_network_cidr: 192.168.0.0/16
openshift_enable_service_catalog: false

# Logging
openshift_logging_install_logging: False
override_openshift_logging_install_logging: True

openshift_logging_install_eventrouter: False
override_openshift_logging_install_eventrouter: True

openshift_metrics_image_version: v3.9
openshift_logging_use_ops: False
openshift_logging_curator_default_days: 30
openshift_logging_kibana_replica_count: 2
openshift_logging_fluentd_audit_container_engine: True
openshift_logging_es_cluster_size: 3
openshift_logging_es_pvc_storage_class_name: glusterfs-storage-block
# This will trigger to call storageclass
openshift_logging_es_pvc_size: "10G"

openshift_hosted_metrics_deploy: False
override_openshift_hosted_metrics_deploy: True
override_openshift_metrics_install_metrics: True
openshift_metrics_install_metrics: False
openshift_metrics_hawkular_hostname: hawkular-metrics.apps.ocp-01.example.com
openshift_metrics_cassandra_limits_memory: 1Gi
openshift_metrics_hawkular_limits_memory: 2Gi
openshift_metrics_heapster_limits_memory: 1Gi

openshift_metrics_cassandra_nodeselector: {"region":"infra"}
#openshift_service_catalog_nodeselector: {"region":"infra"}
openshift_web_console_nodeselector: {'region':'infra'}
openshift_metrics_hawkular_nodeselector: {"region":"infra"}
openshift_metrics_heapster_nodeselector: {"region":"infra"}
openshift_metrics_hawkular_agent_nodeselector: {"region":"infra"}
openshift_metrics_cassandra_storage_type: pv
openshift_metrics_cassandra_pvc_size: 10Gi
openshift_metrics_cassandra_pvc_storage_class_name: glusterfs-storage-block
openshift_metrics_cassanda_pvc_storage_class_name: glusterfs-storage-block

#  Set upgrade restart mode for full system restarts
#openshift_rolling_restart_mode: system

# storage - CRS Configurations
openshift_storage_glusterfs_is_native: False
openshift_storage_glusterfs_registry_is_native: False
openshift_storage_glusterfs_heketi_is_native: True

override_openshift_storage_glusterfs_heketi_is_native: True
glusterfs_heketi_topology_load: False
override_glusterfs_heketi_topology_load: True
openshift_storage_glusterfs_storageclass: False
override_openshift_storage_glusterfs_storageclass: True
glusterfs_block_storageclass: False
override_glusterfs_block_storageclass: True

openshift_storage_glusterfs_heketi_ssh_keyfile: /home/ansible-user/.ssh/id_rsa
openshift_storage_glusterfs_heketi_ssh_user: ansible-user
openshift_storage_glusterfs_heketi_ssh_sudo: True

openshift_storage_glusterfs_storageclass: True
openshift_storage_glusterfs_heketi_executor: ssh
openshift_storage_glusterfs_storageclass_default: True
openshift_storage_glusterfs_block_deploy: True
openshift_storage_glusterfs_block_host_vol_create: True
openshift_storage_glusterfs_block_host_vol_size: 20
openshift_storage_glusterfs_block_host_vol_max: 50
openshift_storage_glusterfs_block_storageclass: True
openshift_storage_glusterfs_image: registry.access.redhat.com/rhgs3/rhgs-server-rhel7
openshift_storage_glusterfs_block_image: registry.access.redhat.com/rhgs3/rhgs-gluster-block-prov-rhel7
openshift_storage_glusterfs_heketi_image: registry.access.redhat.com/rhgs3/rhgs-volmanager-rhel7

openshift_hosted_registry_selector: 'region=infra'

# CONTAINERIZED GLUSTERFS FOR APPLICATIONS, REGISTRY, LOGGING, AND METRICS
# see: https://docs.openshift.org/latest/install_config/persistent_storage/persistent_storage_glusterfs.html
# openshift_metrics_cassanda_pvc_storage_class_name: "glusterfs-registry-block"

# security
os_firewall_use_firewalld: "True"

#openshift_prometheus_pvc_size: 10Gi
#openshift_prometheus_sc_name: glusterfs-storage-block
#openshift_prometheus_storage_type: pvc
#
#openshift_prometheus_alertmanager_pvc_size: 3Gi
#openshift_prometheus_alertmanager_sc_name: glusterfs-storage-block
#openshift_prometheus_alertmanager_storage_type: pvc
#
#openshift_prometheus_alertbuffer_pvc_size: 3Gi
#openshift_prometheus_alertbuffer_sc_name: glusterfs-storage-block
#openshift_prometheus_alertbuffer_storage_type: pvc
